name: ublue main 41
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '5 4 * * *'  # 4am-ish UTC everyday (timed against official fedora container pushes)
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      fedora_version: 41